###############################################################################################################
####### 					CMA Robotics 						#######
###############################################################################################################
# FILE: Load Init
# ATTENTION: don't modify the file to avoid software errors.
#
#
#####################################
#### 	Percorso file e dati 	#####
#####################################
PATH DATA = D:\Programming\Sanding\Painting\New folder\DATI TERMINALE\
#
#####################################
####  Delay PVI		 	#####
#####################################
#
Delay PVI = 20
#
#####################################
#### 	Percorso file Robot	#####
#####################################
DATA PROGRAMS = D:\Programming\Sanding\Painting\New folder\DATI TERMINALE\
DATA PROGRAMS REMOTE = D:\Programming\Sanding\Painting\New folder\DATI TERMINALE\
#
#####################################
####  Configurazione Ethernet	#####
#####################################
#### Per nastro prove ####
CPU ADDRESS = 101.103.107.1
CPU SOURCE STATION = 8
CPU DESTINATION STATION = 0
## Server Ip: Indirizzo Ip del pc dove è presente il Server AxPs, utilizzato per aprire la porta per la comunicazione del robot.  E' necessario che questo indirizzo Ip sia uguale a quello sul robot (Impostazioni -> Avanzate -> Com).
SERVER IP = 101.103.107.217
#
#
#
End